settings:
  scoreboard:
    update: 20
    title: '&6&lSternal&e&lBoard'
    lines:
      - ''
      - '&e&lStatus:'
      - '&7Online: &b%server_online%&7/%server_max_players%'
      - '&7Ping: &b%player_ping%'
      - ''
      - '&7Uptime: &b%server_uptime%'
      - '&7TPS: &b%server_tps%'
      - ''
      - '&7RAM: &b%server_ram_used%&7/&b%server_ram_max%'
      - ''
      - '&etest.minelatin.club'
