settings:
  scoreboard:
    update: 20
    title: '&x&9&3&0&e&0&eS&x&9&d&1&6&1&6t&x&a&6&1&f&1&fe&x&b&0&2&7&2&7r&x&b&9&2&f&2&fn&x&c&3&3&7&3&7a&x&c&d&4&0&4&0l&x&d&6&4&8&4&8B&x&e&0&5&1&5&1o&x&e&9&5&9&5&9a&x&f&3&6&1&6&1r&x&f&d&6&a&6&ad'
    lines:
    - ''
    - '&x&3&a&5&0&a&1I&x&5&2&6&8&b&8n&x&6&a&8&0&c&ff&x&8&2&9&8&e&6o&x&9&a&b&0&f&d:'
    - '&x&8&7&8&e&6&4N&x&8&7&9&3&6&1o&x&8&8&9&8&5&ew &x&8&8&a&1&5&8s&x&8&9&a&6&5&6u&x&8&9&a&b&5&3p&x&8&a&b&0&5&0p&x&8&a&b&5&4&do&x&8&a&b&9&4&ar&x&8&b&b&e&4&7t&x&8&b&c&3&4&5s
      &x&8&c&c&d&3&fh&x&8&c&d&1&3&ce&x&8&d&d&6&3&9x &x&8&d&e&0&3&4c&x&8&e&e&5&3&1o&x&8&e&e&9&2&el&x&8&e&e&e&2&bo&x&8&f&f&3&2&8r&x&8&f&f&8&2&5s&x&9&0&f&c&2&3!'
    - '&7Ping: &b%player_ping%'
    - ''
    - '&7Uptime: &b%server_uptime%'
    - '&7TPS: &b%server_tps%'
    - ''
    - '&7RAM: &b%server_ram_used%&7/&b%server_ram_max%'
    - ''
    - '&x&9&0&6&0&6&0t&x&9&6&5&b&5&be&x&9&c&5&6&5&6s&x&a&2&5&1&5&1t&x&a&8&4&c&4&c.&x&a&e&4&7&4&7m&x&b&4&4&2&4&2i&x&b&a&3&d&3&dn&x&c&0&3&8&3&8e&x&c&6&3&4&3&4l&x&c&c&2&f&2&fa&x&d&2&2&a&2&at&x&d&8&2&5&2&5i&x&d&e&2&0&2&0n&x&e&4&1&b&1&b.&x&e&a&1&6&1&6c&x&f&0&1&1&1&1l&x&f&6&0&c&0&cu&x&f&c&0&8&0&8b'