settings:
  animated: false	#When true, use animated-board.yml
  scoreboard:
    update: 20
    title: '&b&lSternal&f&lBoard'
    lines:
      - '&8&m+-------------------+'
      - ''
      - '&a&l▼ &bData:'
      - '&f● &7Nick: &b%player_name%'
      - '&f● &7Rank: &b%vault_rank%'
      - '&f● &7Coins: &e%vault_eco_balance_formatted%'
      - ''
      - '&a&l▼ &bExample:'
      - '&f● &7Lobby: &b#1'
      - '&f● &7Ping: &b%player_ping%'
      - '&f● &7Players: &b%bungee_total%'
      - ''
      - '&f● &fIP: &bplay.yournetwork.com'