name: SternalBoard
main: com.xIsm4.plugins.Structure
version: 1.8v
api-version: "1.13"
softdepend: [PlaceholderAPI, ViaVersion]

commands:
    sternalboard:
      description: Main command for sternalboard plugin.
      aliases: [sternalboard, sb]

