name: SternalBoard
main: com.xIsm4.plugins.Main
version: 1.13.3
api-version: "1.17"
authors: [xIsm4]
website: https://github.com/xIsm4
softdepend: [PlaceholderAPI]

commands:
    reload:
      description: Reload command for SternalBoard
      aliases: [sternalboard]
    help:
      description: Help command for SternalBoard
      aliases: [ sternalboard ]
    toggle:
        description: Toggle command for SternalBoard
        aliases: [ sternalboard ]
