name: SternalBoard
main: com.xIsm4.plugins.Main
version: 1.1
api-version: "1.13"
authors: [xIsm4]

commands:
    reload:
      description: Reload command for SternalBoard
      aliases: [sternalboard]