name: SternalBoard
main: com.xIsm4.plugins.Structure
version: 1.5
api-version: "1.13"
authors: [xIsm4]
website: https://github.com/xIsm4
softdepend: [PlaceholderAPI]

commands:
    sternalboard:
      description: Main command for sternalboard plugin.
      aliases: [sternalboard]

