name: SternalBoard
main: com.xIsm4.plugins.Main
version: 1.3.5
api-version: "1.13"
authors: [xIsm4]
website: https://github.com/xIsm4
softdepend: [PlaceholderAPI]

commands:
    sternalboard:
      description: Main command for sternalboard
      aliases: [sternalboard]
    toggle:
      description: Command for toggle sternalboard
      aliases: [sbtoggle]
